export const AVATAR_ICONS = [
  { id: "book", emoji: "📚", label: "Libro" },
  { id: "pencil", emoji: "✏️", label: "Lápiz" },
  { id: "star", emoji: "⭐", label: "Estrella" },
  { id: "heart", emoji: "❤️", label: "Corazón" },
  { id: "rocket", emoji: "🚀", label: "Cohete" },
  { id: "graduation", emoji: "🎓", label: "Graduación" },
  { id: "music", emoji: "🎵", label: "Música" },
  { id: "soccer", emoji: "⚽", label: "Deporte" },
  { id: "palette", emoji: "🎨", label: "Arte" },
  { id: "computer", emoji: "💻", label: "Computador" },
  { id: "science", emoji: "🔬", label: "Ciencia" },
  { id: "globe", emoji: "🌍", label: "Mundo" },
  { id: "dog", emoji: "🐶", label: "Perro" },
  { id: "lion", emoji: "🦁", label: "León" },
  { id: "tiger", emoji: "🐯", label: "Tigre" },
  { id: "unicorn", emoji: "🦄", label: "Unicornio" },
  { id: "penguin", emoji: "🐧", label: "Pingüino" },
  { id: "sunflower", emoji: "🌻", label: "Girasol" },
  { id: "cherry", emoji: "🌸", label: "Cerezo" },
  { id: "rainbow", emoji: "🌈", label: "Arcoíris" },
  { id: "moon", emoji: "🌙", label: "Luna" },
  { id: "sun", emoji: "☀️", label: "Sol" },
  { id: "fire", emoji: "🔥", label: "Fuego" },
  { id: "snowflake", emoji: "❄️", label: "Copo de Nieve" },
  { id: "crown", emoji: "👑", label: "Corona" },
  { id: "gem", emoji: "💎", label: "Diamante" },
  { id: "magic", emoji: "🪄", label: "Magia" },
  { id: "trophy", emoji: "🏆", label: "Trofeo" },
  { id: "game", emoji: "🎮", label: "Videojuego" },
  { id: "puzzle", emoji: "🧩", label: "Puzzle" },
  { id: "yoga", emoji: "🧘", label: "Yoga" },
  { id: "party", emoji: "🥳", label: "Fiesta" },
  { id: "compass", emoji: "📐", label: "Compás" },
  { id: "book_open", emoji: "📖", label: "Libro abierto" },
  { id: "abacus", emoji: "🧮", label: "Ábaco" },
  { id: "abc", emoji: "🔤", label: "ABC" },
  { id: "chemistry", emoji: "🧪", label: "Química" },
  { id: "scroll", emoji: "📜", label: "Pergamino" },
  { id: "speaking", emoji: "🗣️", label: "Oratoria" },
  { id: "brain", emoji: "🧠", label: "Cerebro" },
];

export const AVATAR_COLORS = [
    { value: "#8b5cf6", label: "Violeta" }, //{ value: "#000000", label: "Negro" },
    { value: "#f97316", label: "Naranja" }, //{ value: "#FFFFFF", label: "Blanco" },
    { value: "#FF0000", label: "Rojo" },
    { value: "#00FF00", label: "Verde Lima" },
    { value: "#0000FF", label: "Azul" },
    { value: "#FFFF00", label: "Amarillo" },
    { value: "#00FFFF", label: "Cian" },
    { value: "#FF00FF", label: "Magenta" },
    { value: "#808080", label: "Gris" },
    { value: "#FFA500", label: "Naranja" },
    { value: "#800080", label: "Púrpura" },
    { value: "#008080", label: "Teal" },
    { value: "#800000", label: "Granate" },
    { value: "#008000", label: "Verde Bosque" },
    { value: "#000080", label: "Azul Marino" },
    { value: "#FF7F50", label: "Coral" },
];
