export const AVATAR_ICONS = [
  { id: "book", emoji: "📚", label: "Libro" },
  { id: "pencil", emoji: "✏️", label: "Lápiz" },
  { id: "star", emoji: "⭐", label: "Estrella" },
  { id: "heart", emoji: "❤️", label: "Corazón" },
  { id: "rocket", emoji: "🚀", label: "Cohete" },
  { id: "graduation", emoji: "🎓", label: "Graduación" },
  { id: "music", emoji: "🎵", label: "Música" },
  { id: "soccer", emoji: "⚽", label: "Deporte" },
  { id: "palette", emoji: "🎨", label: "Arte" },
  { id: "computer", emoji: "💻", label: "Computador" },
  { id: "science", emoji: "🔬", label: "Ciencia" },
  { id: "globe", emoji: "🌍", label: "Mundo" },
  { id: "cat", emoji: "🐱", label: "Gato" },
  { id: "dog", emoji: "🐶", label: "Perro" },
  { id: "panda", emoji: "🐼", label: "Panda" },
  { id: "fox", emoji: "🦊", label: "Zorro" },
  { id: "rabbit", emoji: "🐰", label: "Conejo" },
  { id: "lion", emoji: "🦁", label: "León" },
  { id: "tiger", emoji: "🐯", label: "Tigre" },
  { id: "unicorn", emoji: "🦄", label: "Unicornio" },
  { id: "penguin", emoji: "🐧", label: "Pingüino" },
  { id: "butterfly", emoji: "🦋", label: "Mariposa" },
  { id: "bee", emoji: "🐝", label: "Abeja" },
  { id: "whale", emoji: "🐳", label: "Ballena" },
  { id: "sunflower", emoji: "🌻", label: "Girasol" },
  { id: "cherry", emoji: "🌸", label: "Cerezo" },
  { id: "rainbow", emoji: "🌈", label: "Arcoíris" },
  { id: "moon", emoji: "🌙", label: "Luna" },
  { id: "sun", emoji: "☀️", label: "Sol" },
  { id: "fire", emoji: "🔥", label: "Fuego" },
  { id: "snowflake", emoji: "❄️", label: "Copo de Nieve" },
  { id: "crown", emoji: "👑", label: "Corona" },
  { id: "gem", emoji: "💎", label: "Diamante" },
  { id: "magic", emoji: "🪄", label: "Magia" },
  { id: "trophy", emoji: "🏆", label: "Trofeo" },
  { id: "game", emoji: "🎮", label: "Videojuego" },
  { id: "puzzle", emoji: "🧩", label: "Puzzle" },
  { id: "yoga", emoji: "🧘", label: "Yoga" },
  { id: "party", emoji: "🥳", label: "Fiesta" },
];

export const AVATAR_COLORS = [
  { value: "#6366f1", label: "Índigo" },
  { value: "#8b5cf6", label: "Violeta" },
  { value: "#ec4899", label: "Rosa" },
  { value: "#ef4444", label: "Rojo" },
  { value: "#f97316", label: "Naranja" },
  { value: "#eab308", label: "Amarillo" },
  { value: "#22c55e", label: "Verde" },
  { value: "#14b8a6", label: "Teal" },
  { value: "#06b6d4", label: "Cian" },
  { value: "#3b82f6", label: "Azul" },
];
